language: go
go:
 - 1.16.x

git:
  depth: 1

script:
 - go test -v ./... -covermode=count -coverprofile=count.out
 
after_success:
 - go get -v github.com/mattn/goveralls
 - goveralls -coverprofile=count.out -service=travis-ci
